name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: yousofkhaled/eyego-node-app
  TAG: latest
  K8S_MANIFEST_PATH: k8s

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$TAG -f docker/Dockerfile docker/

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$TAG

      - name: Remove Local Docker Image
        run: |
          docker rmi $IMAGE_NAME:$TAG || true

      - name: Update Manifest File with Image Tag
        run: |
          sed -i "s|image: .*$|image: $IMAGE_NAME:$TAG|" $K8S_MANIFEST_PATH/deployment.yaml

      - name: Commit Updated Manifests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add $K8S_MANIFEST_PATH/deployment.yaml
          git commit -m "Update image tag to $TAG" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

